# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Number of Rowers')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('rig_type', models.CharField(choices=[('w', 'Sweep'), ('k', 'Skull')], max_length=1, verbose_name='rigging of the boat')),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('c', 'Claire Boat House'), ('r', 'Cambridge Rowing Assosiation')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BoatOrganizer',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='CoxBox',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('c', 'Claire Boat House'), ('r', 'Cambridge Rowing Assosiation')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coxes',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Oars',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number of Oars')),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('c', 'Claire Boat House'), ('r', 'Cambridge Rowing Assosiation')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField(verbose_name='Starting time for the Outing')),
                ('ending_time', models.DateTimeField(verbose_name='Ending time for the Outing')),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Boat')),
            ],
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('preferred_side', models.CharField(choices=[('b', 'Bowside Only'), ('s', 'Strokeside Only'), ('u', 'No Preference yet'), ('bs', 'Mainly Bowside'), ('sb', 'Mainly Strokeside')], max_length=2)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('organizing', models.ManyToManyField(to='organizer.Crew')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rowers',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='outing',
            name='cox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Rower'),
        ),
        migrations.AddField(
            model_name='outing',
            name='coxBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.CoxBox'),
        ),
        migrations.AddField(
            model_name='outing',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Crew'),
        ),
        migrations.AddField(
            model_name='outing',
            name='oars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Oars'),
        ),
    ]
