# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizer.utils.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Number of Rowers')),
                ('gender', organizer.utils.enums.EnumField(choices=[('m', 'Male'), ('f', 'Female')])),
                ('rig_type', organizer.utils.enums.EnumField(choices=[(1, 'Sweep'), (2, 'Skull')], verbose_name='rigging of the boat')),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', organizer.utils.enums.EnumField(choices=[(1, 'Claire Boat House'), (2, 'Cambridge Rowing Assosiation')])),
            ],
        ),
        migrations.CreateModel(
            name='CoxBox',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', organizer.utils.enums.EnumField(choices=[(1, 'Claire Boat House'), (2, 'Cambridge Rowing Assosiation')])),
            ],
        ),
        migrations.CreateModel(
            name='Oars',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('gender', organizer.utils.enums.EnumField(choices=[('m', 'Male'), ('f', 'Female')])),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number of Oars')),
                ('notes', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', organizer.utils.enums.EnumField(choices=[(1, 'Claire Boat House'), (2, 'Cambridge Rowing Assosiation')])),
            ],
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField(verbose_name='Starting time for the Outing')),
                ('ending_time', models.DateTimeField(verbose_name='Ending time for the Outing')),
            ],
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numer', models.CharField(max_length=20)),
                ('preferred_side', organizer.utils.enums.EnumField(choices=[('b', 'Bowside Only'), ('s', 'Strokeside Only'), ('u', 'No Preference yet'), ('b_s', 'Mainly Bowside'), ('s_b', 'Mainly Strokeside')])),
                ('gender', organizer.utils.enums.EnumField(choices=[('m', 'Male'), ('f', 'Female')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
