# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='boat',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coxbox',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coxbox',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='oars',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='oars',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
