# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import organizer.utils.enums


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('organizer', '0002_auto_20160619_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatOrganizer',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Coxes',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('gender', organizer.utils.enums.EnumField(choices=[('m', 'Male'), ('f', 'Female')])),
                ('organizer', models.ManyToManyField(to='organizer.Rower')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Rowers',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.AddField(
            model_name='outing',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Boat'),
        ),
        migrations.AddField(
            model_name='outing',
            name='cox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Rower'),
        ),
        migrations.AddField(
            model_name='outing',
            name='coxBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.CoxBox'),
        ),
        migrations.AddField(
            model_name='outing',
            name='oars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Oars'),
        ),
        migrations.AddField(
            model_name='outing',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.Crew'),
        ),
    ]
