# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20160619_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='organizing',
            field=models.ManyToManyField(blank=True, to='organizer.Crew'),
        ),
        migrations.AlterField(
            model_name='rower',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
